# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# setup_travis

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "assembleDebug")
    gradle(task: "test")
  end

  lane :internal do
    gradle(task: 'clean')
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      track: 'internal',
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_metadata: true
      )
  end

  lane :screenshotPhone do
    gradle(task: 'assembleDebug')
    gradle(task: 'assembleAndroidTest')
    capture_android_screenshots(
        device_type: "phone"
    )
  end

  lane :screenshot7 do
    gradle(task: 'assembleDebug')
    gradle(task: 'assembleAndroidTest')
    capture_android_screenshots(
      device_type: "sevenInch"
    )
   end

  lane :screenshot10 do
    gradle(task: 'assembleDebug')
    gradle(task: 'assembleAndroidTest')
    capture_android_screenshots(
      device_type: "tenInch"
    )
  end

  lane :uploadScreenshots do
      upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_images: true
      )
    end

end
