# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# setup_travis

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "assembleDebug")
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    screenshots
    upload_to_play_store
  end

  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta')
  end

  lane :screenshots do
    gradle(task: 'assembleDebug')
    gradle(task: 'assembleAndroidTest')
    capture_android_screenshots
  end

end
